/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.DataProduct;
import Controller.GestManegmentDataProductsAndOrders;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author pedro
 */
public class InsertProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form InsertProduct
     */
    public InsertProduct() {
        initComponents();
    }
    public void clearInput()
    {   textNameProduct.setText(null);
        textDescProduct.setText(null);
        textPriceProduct.setText(null);
        textQuantityProduct.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        labelNameProduct = new javax.swing.JLabel();
        textNameProduct = new javax.swing.JTextField();
        labelDescProduct = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescProduct = new javax.swing.JTextArea();
        labelPriceProduct = new javax.swing.JLabel();
        textPriceProduct = new javax.swing.JTextField();
        labelPriceProduct1 = new javax.swing.JLabel();
        textQuantityProduct = new javax.swing.JTextField();
        btnCadastrarProduto = new javax.swing.JButton();

        labelNameProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNameProduct.setText("Nome");

        labelDescProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDescProduct.setText("Descrição");

        textDescProduct.setColumns(20);
        textDescProduct.setRows(5);
        jScrollPane1.setViewportView(textDescProduct);

        labelPriceProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPriceProduct.setText("Preço");

        labelPriceProduct1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPriceProduct1.setText("Quantidade");

        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 114, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textNameProduct)
                            .addComponent(jScrollPane1)
                            .addComponent(textPriceProduct)
                            .addComponent(textQuantityProduct, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(labelDescProduct)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(labelPriceProduct1)
                        .addGap(177, 177, 177))))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(labelNameProduct))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(labelPriceProduct))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelNameProduct)
                .addGap(18, 18, 18)
                .addComponent(textNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDescProduct)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPriceProduct)
                .addGap(18, 18, 18)
                .addComponent(textPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPriceProduct1)
                .addGap(18, 18, 18)
                .addComponent(textQuantityProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        
         try {
            DataProduct DC = new DataProduct();
            DC.setNameProduct(textNameProduct.getText());
            DC.setDescriptionProduct(textDescProduct.getText());
            DC.setPriceProduct(Double.parseDouble(textPriceProduct.getText()));
            DC.setQuantityProduct(Integer.parseInt(textQuantityProduct.getText()));
            GestManegmentDataProductsAndOrders GMDPA = new GestManegmentDataProductsAndOrders();
            GMDPA.insertProduct(DC);
            JOptionPane.showMessageDialog(null, "Produto cadastrado no DB", "sucesso", 1);
            clearInput();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto no DB\nCausa: " + error.getMessage(), "ERRO", 1);
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDescProduct;
    private javax.swing.JLabel labelNameProduct;
    private javax.swing.JLabel labelPriceProduct;
    private javax.swing.JLabel labelPriceProduct1;
    private javax.swing.JTextArea textDescProduct;
    private javax.swing.JTextField textNameProduct;
    private javax.swing.JTextField textPriceProduct;
    private javax.swing.JTextField textQuantityProduct;
    // End of variables declaration//GEN-END:variables
}
