/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculoIMC;

import javax.swing.JOptionPane;

/**
 *
 * @author 182120037
 */
public class AppIMC extends javax.swing.JFrame {

    /**
     * Creates new form AppIMC
     */
    public AppIMC() {
        initComponents();
  
    }// contructor

    double peso;
    double altura;
    double calculo;
    int resultado;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BotaoHomen = new javax.swing.JRadioButton();
        BotaoMulher = new javax.swing.JRadioButton();
        Peso = new javax.swing.JTextField();
        Altura = new javax.swing.JTextField();
        Text_Peso = new javax.swing.JLabel();
        Text_Altura = new javax.swing.JLabel();
        Icone_Equals = new javax.swing.JLabel();
        ResultadoIMC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(172, 172, 172));

        Botoes.add(BotaoHomen);
        BotaoHomen.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        BotaoHomen.setText("Homen");
        BotaoHomen.setToolTipText("Para novo calculo clique novamente");
        BotaoHomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHomenActionPerformed(evt);
            }
        });

        Botoes.add(BotaoMulher);
        BotaoMulher.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        BotaoMulher.setText("Mulher\n");
        BotaoMulher.setToolTipText("Para novo cálculo clique novamente.");
        BotaoMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMulherActionPerformed(evt);
            }
        });

        Peso.setBackground(new java.awt.Color(255, 255, 255));
        Peso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Peso.setForeground(new java.awt.Color(0, 0, 0));
        Peso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Peso.setToolTipText("");

        Altura.setBackground(new java.awt.Color(255, 255, 255));
        Altura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Altura.setForeground(new java.awt.Color(0, 0, 0));
        Altura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Text_Peso.setBackground(new java.awt.Color(255, 255, 255));
        Text_Peso.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Text_Peso.setForeground(new java.awt.Color(255, 255, 255));
        Text_Peso.setText("Digite o peso");

        Text_Altura.setBackground(new java.awt.Color(255, 255, 255));
        Text_Altura.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Text_Altura.setForeground(new java.awt.Color(255, 255, 255));
        Text_Altura.setText("Digite altura em Cm");

        Icone_Equals.setBackground(new java.awt.Color(255, 255, 255));
        Icone_Equals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Equals_sign_in_mathematics.jpg"))); // NOI18N
        Icone_Equals.setMaximumSize(new java.awt.Dimension(100, 25));
        Icone_Equals.setMinimumSize(new java.awt.Dimension(20, 15));

        ResultadoIMC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ResultadoIMC.setForeground(new java.awt.Color(0, 0, 0));
        ResultadoIMC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ResultadoIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoIMCActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IMC.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ResultadoIMC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Text_Peso)
                                        .addGap(93, 93, 93)
                                        .addComponent(Text_Altura))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(292, 292, 292)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoMulher, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoHomen, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(Icone_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BotaoHomen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoMulher, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Icone_Equals, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResultadoIMC, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(2084, 2084, 2084))
        );

        Text_Peso.getAccessibleContext().setAccessibleName("Text peso");
        jLabel1.getAccessibleContext().setAccessibleName("BannerIMC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addGap(485, 485, 485))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1894, Short.MAX_VALUE)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(704, 704, 704))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMulherActionPerformed

        try {
            peso = Double.parseDouble(Peso.getText().replace(",", "."));
            altura = Double.parseDouble(Altura.getText().replace(",", "."));
            calculo = peso / (altura*altura);
            if (calculo < 19.1){ ResultadoIMC.setText("Imc: "+calculo+ " Você está abaixo do peso ");}// END IF
            else if (calculo >= 19.1 & calculo <= 25.8){ResultadoIMC.setText("IMC: "+calculo+ " você está no peso normal");}// END ELSE IF
            else if (calculo >= 25.9 & calculo <= 27.3){ResultadoIMC.setText("IMC: "+calculo+ " você está pouco acima do peso");}// END ELSE IF
            else if (calculo >= 27.4 & calculo <= 32.3){ResultadoIMC.setText("IMC: "+calculo+ " você está acima do peso");}// END ELSE IF
            else if (calculo >= 32.4) {ResultadoIMC.setText("Obesidade Extrema");}
            else {ResultadoIMC.setText("Não é humano");}
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"mensagem\nCausa: "+e.getMessage(),"título",JOptionPane.ERROR_MESSAGE);

        }// END catch
    }//GEN-LAST:event_BotaoMulherActionPerformed

    private void BotaoHomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHomenActionPerformed
        try {
            peso = Double.parseDouble(Peso.getText());
            altura = Double.parseDouble(Altura.getText().replace(",", "."));
            calculo = peso / (altura*altura);
            if (calculo < 19.1){
                Resultado.setText("Imc: "+calculo+". Você está ");
            }// END IF
            else if (calculo >= 19.1 & calculo <= 25.8){ResultadoIMC.setText("IMC: "+calculo+ " você está no peso normal");}// END ELSE IF
            else if (calculo >= 25.9 & calculo <= 27.3){ResultadoIMC.setText("IMC: "+calculo+ " você está pouco acima do peso");}// END ELSE IF
            else if (calculo >= 27.4 & calculo <= 32.3){ResultadoIMC.setText("IMC: "+calculo+ " você está acima do peso");}// END ELSE IF
            else if (calculo >= 32.4) {ResultadoIMC.setText("Obesidade Extrema");}
            else {ResultadoIMC.setText("Não é humano");}
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"mensagem\nCausa: "+e.getMessage(),"título",JOptionPane.ERROR_MESSAGE);

        }// END catch

    }//GEN-LAST:event_BotaoHomenActionPerformed

    private void ResultadoIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Altura;
    private javax.swing.JRadioButton BotaoHomen;
    private javax.swing.JRadioButton BotaoMulher;
    private javax.swing.ButtonGroup Botoes;
    private javax.swing.JLabel Icone_Equals;
    private javax.swing.JTextField Peso;
    private javax.swing.JLabel Resultado;
    private javax.swing.JTextField ResultadoIMC;
    private javax.swing.JLabel Text_Altura;
    private javax.swing.JLabel Text_Peso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
