/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import java.awt.Color;
import java.awt.Desktop;
import static java.awt.SystemColor.desktop;
import java.awt.Toolkit;
import java.net.URI;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 182120037
 */
public class InterfaceIMC extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceIMC
     */
    public InterfaceIMC() {
        initComponents();
        // centralizar app na tela
        setLocationRelativeTo(null);
        // desmarcar botão maxumizar
        setResizable(false);
        // menssagem
        JOptionPane.showMessageDialog(null,"Bem vindo ao sistema deIMC\n\nCOPYRIGHT ®LP","Bem vindo",JOptionPane.PLAIN_MESSAGE);
        // colocar log no Jframe
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Image/logoJframe.jpg")));
    }
    
    //Create variables
      double Peso,Altura,IMC;
    // Create vetor from images
      private Icon ImageMAn[] = {
              new ImageIcon(getClass().getResource("../Image/homemgordo.jpg")),
              new ImageIcon(getClass().getResource("../Image/homemmagro.jpg")),
              new ImageIcon(getClass().getResource("../Image/homempesoideal.jpg"))    
      };
      private Icon ImageGirl[] = {
              new ImageIcon(getClass().getResource("../Image/mulhergorda.jpg")),
              new ImageIcon(getClass().getResource("../Image/mulhermagra.jpg")),
              new ImageIcon(getClass().getResource("../Image/mulherpesoideal.jpg"))
      };
      
      int foto;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PainelDados = new javax.swing.JPanel();
        LabelPeso = new javax.swing.JLabel();
        LabelAltura = new javax.swing.JLabel();
        LabelGênero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPeso = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAltura = new javax.swing.JTextPane();
        EscolhaSexo = new javax.swing.JComboBox<>();
        PainelResultado = new javax.swing.JPanel();
        LabelResultadoIMC = new javax.swing.JLabel();
        labelimagem = new javax.swing.JLabel();
        BotãoCalcular = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoLink = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icone.png"))); // NOI18N

        PainelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Code Pro ExtraLight", 1, 14))); // NOI18N

        LabelPeso.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LabelPeso.setText("peso:");
        LabelPeso.setToolTipText("Peso:");

        LabelAltura.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LabelAltura.setText("Altura");
        LabelAltura.setToolTipText("Peso:");

        LabelGênero.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LabelGênero.setText("Gênero: ");
        LabelGênero.setToolTipText("Peso:");

        TextPeso.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(TextPeso);

        TextAltura.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(TextAltura);

        EscolhaSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "**********", "MASCULINO", "FEMININO", " " }));
        EscolhaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaSexoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelDadosLayout = new javax.swing.GroupLayout(PainelDados);
        PainelDados.setLayout(PainelDadosLayout);
        PainelDadosLayout.setHorizontalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(LabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addComponent(LabelGênero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EscolhaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        PainelDadosLayout.setVerticalGroup(
            PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDadosLayout.createSequentialGroup()
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDadosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGênero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscolhaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        PainelResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Source Code Pro ExtraLight", 1, 14))); // NOI18N

        LabelResultadoIMC.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        LabelResultadoIMC.setText("IMC: ");
        LabelResultadoIMC.setBorder(null);

        javax.swing.GroupLayout PainelResultadoLayout = new javax.swing.GroupLayout(PainelResultado);
        PainelResultado.setLayout(PainelResultadoLayout);
        PainelResultadoLayout.setHorizontalGroup(
            PainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResultadoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LabelResultadoIMC, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PainelResultadoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelResultadoLayout.setVerticalGroup(
            PainelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelResultadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelResultadoIMC)
                .addGap(31, 31, 31)
                .addComponent(labelimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        BotãoCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconecalculo.jpg"))); // NOI18N
        BotãoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoCalcularActionPerformed(evt);
            }
        });

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconelimpar.jpg"))); // NOI18N
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/64673.png"))); // NOI18N
        botaoLink.setToolTipText("buscar infos IMC");
        botaoLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(623, 623, 623))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotãoCalcular)
                        .addGap(27, 27, 27)
                        .addComponent(botaoLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoLink, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(PainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(992, 992, 992))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(PainelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PainelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotãoCalcular)
                            .addComponent(botaoLimpar)
                            .addComponent(botaoLink, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscolhaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolhaSexoActionPerformed

    private void BotãoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoCalcularActionPerformed
 try {        
// pegar os valores digitas na inteface  na esquerda 
        Peso = Double.parseDouble(TextPeso.getText());
        Altura = Double.parseDouble(TextAltura.getText().replace(",", "."));
        IMC = Peso / (Math.pow(Altura, 2));
        // pegar a escolha do genero Escolhido na interface
        switch (EscolhaSexo.getSelectedIndex()){
        
            case 0 : 
                EscolhaSexo.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Escolha de gênero obrigatória","Error",JOptionPane.ERROR_MESSAGE);
                EscolhaSexo.setBackground(Color.white);
                break;
            case 1:
                // masculino 
                if (IMC >= 25){LabelResultadoIMC.setText(String.format("você está acima do peso. IMC: %.1f", IMC));
                foto = 0;}
                else if (IMC < 24.9 & IMC > 19 ){LabelResultadoIMC.setText(String.format("você está  no peso ideal. IMC: %.1f", IMC));
                foto = 2;}
                else {LabelResultadoIMC.setText(String.format("você está magro. IMC: %.1f", IMC));
                 foto = 1;} 
                labelimagem.setIcon(ImageMAn[foto]);
                break;
            case 2:
                // Feminino 
                 if (IMC >= 24){LabelResultadoIMC.setText(String.format("você está acima do peso. IMC: %.1f", IMC));
                foto = 0;}
                else if (IMC < 23 & IMC > 18 ){LabelResultadoIMC.setText(String.format("você está acima no peso ideal. IMC: %.1f", IMC));
                foto = 2;}
                else {LabelResultadoIMC.setText(String.format("você está magro. IMC: %.1f", IMC));
                 foto = 1;}
                
                labelimagem.setIcon(ImageGirl[foto]);
                break;
        
        
        }// END switch case escolhaSEXO
 }
 catch (NumberFormatException erro){
 JOptionPane.showMessageDialog(null, "erro", "erro na digitação",JOptionPane.ERROR_MESSAGE);
 TextPeso.setText("");
 TextAltura.setText("");
 Peso = 0;
 Altura = 0;
 JOptionPane.showMessageDialog(null, "Sistema Limpo");
 }
    }//GEN-LAST:event_BotãoCalcularActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // METODO LIMPAR
        EscolhaSexo.setSelectedIndex(0);
        TextPeso.setText("");
        TextAltura.setText("");
        LabelResultadoIMC.setText("");
        labelimagem.setIcon(null);
        JOptionPane.showMessageDialog(null, "limpo", "sistema pronto para novo calculo", WIDTH);
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLinkActionPerformed
        // TODO add your handling code here:
        try {
        URI link = new URI ("https://www.programasaudefacil.com.br/calculadora-de-imc");
        Desktop.getDesktop().browse(link);
        }catch (Exception erro){JOptionPane.showMessageDialog(null, "erro", "Erro na URL\n causa: "+erro.getMessage(), WIDTH);}
    }//GEN-LAST:event_botaoLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoCalcular;
    private javax.swing.JComboBox<String> EscolhaSexo;
    private javax.swing.JLabel LabelAltura;
    private javax.swing.JLabel LabelGênero;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelResultadoIMC;
    private javax.swing.JPanel PainelDados;
    private javax.swing.JPanel PainelResultado;
    private javax.swing.JTextPane TextAltura;
    private javax.swing.JTextPane TextPeso;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelimagem;
    // End of variables declaration//GEN-END:variables
} 

